name: flutter_project
description: A Flutter project that showcases various algorithms.
publish_to: 'none' 

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.0
  google_fonts: ^2.1.0
  flutter_flow: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true